inherit_from: .rubocop_todo.yml

require: rubocop-rails
require: rubocop-rspec
require: rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'


Metrics/LineLength:
  Enabled: false
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
